version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql

  app:
    build: .
    ports:
      - "8083:8080"
    depends_on:
      - mysql
