server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  application:
    name: user-service
  eureka:
    instance:
      prefer-ip-address: true
    client:
      service-url:
        default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
